# Generated by Django 2.2 on 2020-09-04 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('assigned_vehicle', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Sacco Admin', 'Sacco Admin'), ('Owner', 'Owner'), ('Tout', 'Tout'), ('Driver', 'Driver'), ('Passenger', 'Passenger'), ('MOH', 'MOH'), ('NTSA', 'NTSA'), ('KRA', 'KRA'), ('INTERIOR', 'INTERIOR')], default='Sacco Admin', max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('pickup_at', models.CharField(max_length=255, null=True)),
                ('drop_at', models.CharField(max_length=255, null=True)),
                ('confirmed', models.BooleanField(default=False, null=True)),
                ('passenger_name', models.CharField(default='Anonymous', max_length=255)),
                ('passenger_phone', models.CharField(default='Not recorded', max_length=255)),
                ('fare', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('PesaLink', 'PesaLink')], default='Mpesa', max_length=255)),
                ('seat_no', models.IntegerField(default=0)),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_trip_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starting_from', models.CharField(max_length=255)),
                ('ending_at', models.CharField(max_length=255)),
                ('minRate', models.CharField(max_length=255)),
                ('maxRate', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('paybill', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.CharField(max_length=255)),
                ('tlb', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('routes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.Routes')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacco', to='core.Sacco')),
                ('tout', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seats_no', models.CharField(max_length=255)),
                ('driver_seat_no', models.CharField(max_length=255)),
                ('tout_seat_no', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
                ('amount', models.CharField(max_length=255)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_user_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('starting_from', models.CharField(max_length=255)),
                ('ending_at', models.CharField(max_length=255)),
                ('max_rate', models.CharField(default=0, max_length=255)),
                ('min_rate', models.CharField(default=0, max_length=255)),
                ('price', models.CharField(default=0, max_length=255)),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trip_driver', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trip_sacco', to='core.Sacco')),
                ('tout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trip_tout', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trip', to='core.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicleType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type', to='core.VehicleType'),
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('seatNo', models.CharField(max_length=255)),
                ('occStatus', models.BooleanField(default=False)),
                ('payStatus', models.BooleanField(default=False)),
                ('vehicleTrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trip_seat', to='core.VehicleTrip')),
            ],
        ),
        migrations.AddField(
            model_name='routes',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_sacco', to='core.Sacco'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('amount', models.CharField(max_length=255)),
                ('passenger_name', models.CharField(max_length=255)),
                ('passenger_phone', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('seatNo', models.CharField(max_length=255)),
                ('passTrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_trip_payment', to='core.PassengerTrip')),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_trip_payment_user', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_trip_sacco_payment', to='core.Sacco')),
                ('vehicleTrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trip_payment', to='core.VehicleTrip')),
            ],
        ),
        migrations.AddField(
            model_name='passengertrip',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_trip_sacco', to='core.Sacco'),
        ),
        migrations.AddField(
            model_name='passengertrip',
            name='vehicleTrip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_vehicle_trip', to='core.VehicleTrip'),
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_id', models.CharField(default='', max_length=225)),
                ('transaction_type', models.CharField(default='', max_length=225)),
                ('paybill_no', models.CharField(default='', max_length=225)),
                ('reference', models.CharField(max_length=225)),
                ('first_name', models.CharField(max_length=225)),
                ('middle_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=225)),
                ('organization_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sacco', to='core.Sacco'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
